name: chelepa.net CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Deploy para meu Hosting
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          ARGS:
          SOURCE:
          TARGET:  ${{ secrets.TARGET }}

  created-config-Hostinger:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ${{secrets.TARGET}}
            echo "
              MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
              MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}
              MYSQL_HOST=${{ secrets.MYSQL_HOST }}
              MYSQL_PORT=${{ secrets.MYSQL_PORT }}
              MYSQL_DB=${{ secrets.MYSQL_DB }}
              TARGET=${{ secrets.TARGET }}
            " > .env

#  deploy-Hostinger:
#    runs-on: ubuntu-latest
#    needs: created-config-Hostinger
#    steps:
#      - name: executing remote ssh commands
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.REMOTE_PORT }}
#          script: |
#            cd ${{secrets.TARGET}}
#            docker stop BarberShop
#            docker rm BarberShop
#            docker rmi barbershop-backend
#            docker-compose up -d
